### ISSUE TITLE
Other ports?

### ISSUE THREAD

**Issue by reflog** [mietzen/docker-redsocks-proxy#11]
Hey @mietzen !
Thanks for this nice redsocks setup. Very cleanly done.
This only funnels 80 & 443, right? Anything else is unproxied?

I tried editing the entrypoint to have this rule instead: 
`iptables -t nat -A OUTPUT -p tcp -j REDIRECT --to-port "$LOCAL_PORT"`
but that doesen't seem to work 🤔

**Comment by mietzen** [comment]
Thanks, you can easily change this by overwriting the [`entrypoint.sh`](https://github.com/mietzen/docker-redsocks-proxy/blob/main/entrypoint.sh).

Just download it and save it into a folder, e.g. `redsocks`:


```shell
mkdir redsocks
cd redsocks
wget https://raw.githubusercontent.com/mietzen/docker-redsocks-proxy/refs/heads/main/entrypoint.sh
```

Then edit the downloaded file:

**a)** Add another / Change the current - Port:

```shell
iptables -t nat -A OUTPUT -p tcp --dport <YOUR_PORT> -j REDIRECT --to-port "$LOCAL_PORT"
```

at Line: https://github.com/mietzen/docker-redsocks-proxy/blob/95689c029f581ab967e66807092b9ee582636cf9/entrypoint.sh#L49

**or**

**b)** redirect <ins>**all**</ins> TCP traffic, by replacing the lines with:

```shell
iptables -t nat -A OUTPUT -p tcp -j REDIRECT --to-port "$LOCAL_PORT"
```

Afterward edit your [`docker-compose.yaml`](https://github.com/mietzen/docker-redsocks-proxy/blob/main/docker-compose.yaml) file:

```yaml
  ...
  redsocks:
    image: mietzen/redsocks-proxy:stable
    hostname: redsocks
    volumes:
      - ./redsocks:/redsocks
    entrypoint: /redsocks/entrypoint.sh
    ...
```

Depending on the docker host OS you might also be able to directly volume mount the file (I know that Windows / WSL has or had problems with that).

```yaml
  ...
  redsocks:
    image: mietzen/redsocks-proxy:stable
    hostname: redsocks
    volumes:
      - ./redsocks/entrypoint.sh:/entrypoint.sh
    ...
```

**Comment by reflog** [comment]
thanks so much for the detailed explanation @mietzen but for some reason, redirecting all traffic doesn't see to work

here's my compose using the original entrypoint:
```
services:
  redsocks:
    image: mietzen/redsocks-proxy:stable
    volumes:
      # - ./entrypoint.sh:/entrypoint.sh
      - ./entrypoint_orig.sh:/entrypoint.sh
    hostname: redsocks
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - PROXY_SERVER=************
      - PROXY_PORT=7777
      - LOGIN="************"
      - PASSWORD="************"
      - LOG_DEBUG=on
      - LOG_FILE=stdout
    dns: 9.9.9.9 # Optional
    restart: unless-stopped

  debian:
    image: mietzen/debian-curl-jq:stable
    depends_on:
      - redsocks
    network_mode: service:redsocks
    command: /bin/bash -c "while true; do curl -sSL https://ipconfig.io && sleep 10; done"
    restart: unless-stopped
```

this works great.

when I switch to the new entrypoint.sh : 
```
#!/bin/bash

set -e

# Set default values for optional variables
export LOG_DEBUG=${LOG_DEBUG:-off}
export LOG_INFO=${LOG_INFO:-on}
export LOG_FILE="${LOG_FILE:-/var/log/redsocks.log}"
export LOG="\"file:${LOG_FILE}\""
export LOCAL_IP=${LOCAL_IP:-127.0.0.1}
export LOCAL_PORT=${LOCAL_PORT:-8081}
export PROXY_TYPE=${PROXY_TYPE:-socks5}
export TCP_KEEPALIVE_TIME=${TCP_KEEPALIVE_TIME:-0}
export TCP_KEEPALIVE_PROBES=${TCP_KEEPALIVE_PROBES:-0}
export TCP_KEEPALIVE_INTVL=${TCP_KEEPALIVE_INTVL:-0}
export RLIMIT_NOFILE=${RLIMIT_NOFILE:-0}
export REDSOCKS_CONN_MAX=${REDSOCKS_CONN_MAX:-0}
export CONNPRES_IDLE_TIMEOUT=${CONNPRES_IDLE_TIMEOUT:-7440} # Default is 2 hours 4 minutes (RFC 5382)
export MAX_ACCEPT_BACKOFF=${MAX_ACCEPT_BACKOFF:-60000}
export ON_PROXY_FAIL=${ON_PROXY_FAIL:-close}
export DISCLOSE_SRC=${DISCLOSE_SRC:-false}
export LISTENQ=${LISTENQ:-128}
export SPLICE=${SPLICE:-false}

# Validate mandatory variables
if [ -z "$PROXY_SERVER" ] || [ -z "$PROXY_PORT" ]; then
  echo "Error: PROXY_SERVER and PROXY_PORT must be set."
  exit 1
fi

# Generate the configuration file
echo "Generating Redsocks configuration..."
envsubst </etc/redsocks.conf.template >/etc/redsocks.conf

# Remove both login and password if either is unset
if [ -z "$LOGIN" ] || [ -z "$PASSWORD" ]; then
  sed -i '/login = /d' /etc/redsocks.conf
  sed -i '/password = /d' /etc/redsocks.conf
fi

# Print final configuration for debugging
echo "Final Redsocks configuration (sensitive data redacted):"
sed -e 's/\(login = \).*/\1***;/' -e 's/\(password = \).*/\1***;/' /etc/redsocks.conf

# Restart Redsocks service and configure iptables
echo "Restarting Redsocks and configuring iptables..."
/etc/init.d/redsocks restart

iptables -t nat -A OUTPUT -p tcp -j REDIRECT --to-port "$LOCAL_PORT"
#iptables -t nat -A OUTPUT -p tcp --dport 80 -j REDIRECT --to-port "$LOCAL_PORT"
#iptables -t nat -A OUTPUT -p tcp --dport 443 -j REDIRECT --to-port "$LOCAL_PORT"
echo "Container IP Address: $(curl -sSL https://v4.ident.me)"
tail -f "$LOG_FILE"
```

it get's stuck when trying to get container IP

redirection in iptables is working, because I can see in redsocks logs:
`1733409967.104992 info redsocks.c:1243 redsocks_accept_client(...) [172.21.0.2:46710->x.x.x.x:7777]: accepted`


any ideas what could be the issue?
